name: Hello World CI

on: 
  push:

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3

   - name: Print Hello World
     run: echo "Hello World"
     
   - name: Print secret
     run: echo $MY_SECRET
     env: 
       MY_SECRET: ${{ secrets.MY_SECRET }}

   - name: Execute bash script
     run: bash run.sh

   - name: Build docker Image of BE
     run: docker build -t maxxxxxxx/backend-image-gallery nypag-spring_backend-5b58b4e2560c

   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
        username: maxxxxxxx
        password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Set up JDK 18
     uses: actions/setup-java@v4
     with:
      java-version: '18'
      distribution: 'adopt'
 
   - name: Setup Gradle
     uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
 
   - name: Build with Gradle
     run: nypag-spring_backend-5b58b4e2560c

   - name: Push to Docker Hub
     run: docker push maxxxxxxx/backend-image-gallery
