name: Hello World CI

on: 
  push:

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3

   - name: Print Hello World
     run: echo "Hello World"
     
   - name: Print secret
     run: echo $MY_SECRET
     env: 
       MY_SECRET: ${{ secrets.MY_SECRET }}

   - name: Execute bash script
     run: bash run.sh

   - name: executing remote ssh commands using password
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.JUMP_HOST }}
      username: ${{ secrets.JUMP_USERNAME }}
      password: ${{ secrets.JUMP_PASSWORD }}
      proxy_host: ${{ secrets.PROXY_HOST }}
      proxy_username: ${{ secrets.PROXY_USERNAME }}
      proxy_password: ${{ secrets.PROXY_PASSWORD}}
      script: echo "Hello World"

  
   # Step 2: Set up JDK 18 for Gradle
   - name: Set up JDK 19
     uses: actions/setup-java@v2
     with:
          java-version: '19'
          distribution: 'adopt'
 
      # Step 3: Set up Gradle build environment
   - name: Set up Gradle
     uses: gradle/gradle-build-action@v2
 
      # Step 4: Build the application with Gradle
   - name: Build with Gradle
     run: nypag-spring_backend-5b58b4e2560c/gradle build
 
      # Step 5: Run unit tests with Gradle
   - name: Run tests with Gradle
     run: gradle test

   - name: Build docker Image of BE
     run: docker build -t maxxxxxxx/backend-image-gallery nypag-spring_backend-5b58b4e2560c

   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
        username: maxxxxxxx
        password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Push to Docker Hub
     run: docker push maxxxxxxx/backend-image-gallery
